name: Outputs
on: 
  - workflow_dispatch

jobs: 
  set-and-get-color:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      
      - name: Get color
        run: echo "${{ steps.color-generator.outputs.SELECTED_COLOR }}"
