name: Outputs
on: 
  - workflow_dispatch

jobs: 
  set-and-get-color:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      
      - name: Get color
        run: echo "${{ steps.color-generator.outputs.SELECTED_COLOR }}"

  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
            the_secret=$((RANDOM))
            echo "::add-mask::$the_secret"
            echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      
      - name: Use that secret output (protected by a mask)
        run: |
            echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"


  add-environment-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
            echo "action_state=yellow" >> "$GITHUB_ENV"
      - run: |
            echo "${{ env.action_state}}"

  add-summaries:
    runs-on: ubuntu-latest
    steps:
      - run: echo "### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
      - run: echo "### Love this feature! :medal_sports:' >> $GITHUB_STEP_SUMMARY
      - run: echo "<h1>Great feature!</h1>' >> $GITHUB_STEP_SUMMARY
